import { useEffect, useState } from "react";
import { api } from "../api/client.js";
import { StatCard, Loader, ErrorNote, EmptyState } from "../components/ui.jsx";

export default function DoctorDashboard() {
  const [patients, setPatients] = useState([]);
  const [population, setPopulation] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [summary, setSummary] = useState(null);
  const [summaryLoading, setSummaryLoading] = useState(false);

  useEffect(() => {
    Promise.all([api.allPatients(), api.population()])
      .then(([p, pop]) => { setPatients(p); setPopulation(pop); })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  async function genSummary(patient) {
    setSummary({ patient });
    setSummaryLoading(true);
    try {
      const res = await api.aiSummary(patient.id);
      setSummary({ patient, text: res.summary });
    } catch (e) {
      setSummary({ patient, text: `⚠️ ${e.message}` });
    } finally {
      setSummaryLoading(false);
    }
  }

  if (loading) return <Loader label="Loading clinical dashboard…" />;

  return (
    <div className="grid" style={{ gap: 22 }}>
      <div className="page-head">
        <h1>👨‍⚕️ Provider Portal</h1>
        <p>Clinical intelligence — patient overviews and AI pre-visit summaries.</p>
      </div>

      <ErrorNote message={error} />

      {population && (
        <div className="grid cols-3">
          <StatCard icon="👥" value={population.total_patients} label="Total patients" accent="#0ea5e9" />
          <StatCard icon="✅" value={`${Math.round(population.avg_adherence * 100)}%`} label="Avg adherence" accent="#10b981" />
          <StatCard icon="⚠️" value={population.high_risk_patients.length} label="High-risk patients" accent="#ef4444" />
        </div>
      )}

      <div className="grid" style={{ gridTemplateColumns: "1.3fr 1fr" }}>
        <div className="card">
          <h3 className="card-title">Patient list</h3>
          <p className="card-sub">Select a patient for an AI pre-visit summary</p>
          {patients.length === 0 ? (
            <EmptyState icon="👥" title="No patients" />
          ) : patients.map((p) => (
            <div className="list-row" key={p.id}>
              <div className="lead">
                <div className="dot">🧑</div>
                <div>
                  <div style={{ fontWeight: 700 }}>{p.name}</div>
                  <div className="muted" style={{ fontSize: ".82rem" }}>{p.conditions || "No conditions recorded"}</div>
                </div>
              </div>
              <div className="row">
                <span className={"badge " + (p.adherence_rate < 0.7 ? "red" : "green")}>
                  {Math.round(p.adherence_rate * 100)}% adherence
                </span>
                <button className="btn sm" onClick={() => genSummary(p)}>AI summary</button>
              </div>
            </div>
          ))}
        </div>

        <div className="card">
          <h3 className="card-title">🧠 AI pre-visit summary</h3>
          <p className="card-sub">Generated by the Clinical agent</p>
          {!summary ? (
            <EmptyState icon="📄" title="No summary yet" hint="Click 'AI summary' on a patient." />
          ) : (
            <>
              <div style={{ fontWeight: 700, marginBottom: 8 }}>{summary.patient.name}</div>
              {summaryLoading ? (
                <div className="pulse muted">🧠 Generating summary…</div>
              ) : (
                <div style={{ whiteSpace: "pre-wrap", lineHeight: 1.55 }}>{summary.text}</div>
              )}
            </>
          )}
        </div>
      </div>

      {population?.high_risk_patients?.length > 0 && (
        <div className="card" style={{ background: "#fef2f2", borderColor: "#fecaca" }}>
          <h3 className="card-title">⚠️ High-risk patients (adherence &lt; 70%)</h3>
          {population.high_risk_patients.map((p) => (
            <div className="list-row" key={p.id}>
              <div className="lead"><div className="dot">🚩</div><div style={{ fontWeight: 700 }}>{p.name}</div></div>
              <span className="badge red">{Math.round(p.adherence_rate * 100)}% · {p.missed_doses} missed</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
